apiVersion: v1
stringData:
    SECRETNAME: ENC[AES256_GCM,data:1puJtKQWp6tbT9w=,iv:POR2x0MUf0AeA8DKjd52lJ888nYqWgc7QtHPwY79doE=,tag:loAXU+UQIowTJ8ympIWVtw==,type:str]
kind: Secret
metadata:
    name: showenv-secret
type: Opaque
sops:
    age:
        - recipient: age19kyyjnd32na99sn2d4ktqddykrmnghu6tk34fsy9l9duyu2g95ssypk7vy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3b3MwcEhkUS9qdU15TUl6
            TmYreTUyanI0MnFNWFd2TE9WL2pEU0xZRmtBCkR2bU04eTJISXp4aXBCaWdFVms2
            VXpLT2huWlVaRytnRzc4WGpNL2VjQ0UKLS0tIEJHK3VJTnVWN0x5cDBwUkl2ZjBU
            dElqa0hYczJOcUNRQUROZmFkcDArL0kKB9vufvA20bxlTb7oa2QjPpamrZtchdb+
            hT5VvQ9UAJuk2F9UIjSis44ja8UzO1hREsDPw8nWrbgknCemCg5t+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T10:19:15Z"
    mac: ENC[AES256_GCM,data:DHUdL48y9x/Xpi5ye/0rLtmcOr1wU1pmMDUwVdxdWZYBO95avm6QbCv7s8Pepzt3QZIKnFNn9EHXiFK8wkGG55Zee5ZAjr1EJU3Hd+4kntDSoCnaOXrRHQwLEC+96zlnIrt+cQUfVt+UgcxOEIxmN5yXgfTZvjTYaQ72HXajOv4=,iv:Nsafl+v3YfU8gw2X0kAUVedX+GKv35boStnX1RuMXmc=,tag:xhOOuZ9WlOfZxQBHgMPdiA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
