apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - ../../base/helloworld
    - tls-secret.yaml
namespace: demo
images:
    - name: helloworld
      newName: k3d-registry.127.0.0.1.nip.io:5000/helloworld
      newTag: v0.1.0
patches:
    - patch: |-
        - op: replace
          path: /spec/rules/0/host
          value: helloworld-local.training.jambit.space
        - op: replace
          path: /spec/tls/0/hosts/0
          value: helloworld-local.training.jambit.space
      target:
        kind: Ingress
configMapGenerator:
    - name: helloworld-config
      literals:
        - NAME=local
secretGenerator:
    - name: helloworld-secret
      literals:
        - SECRETNAME=WORLD2
