apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- ingress.yaml
- service.yaml

configMapGenerator:
- name: showenv-config

secretGenerator:
- name: showenv-secret